name: pubspec_ui
description: Manage pubspecs yaml/lock file
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  path: ^1.8.3
  url_launcher: ^6.1.11
  yaml: ^3.1.2
  http: ^0.13.6
  html: ^0.15.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
